import type { ResumeStructure } from './types';

// ponytail: offline stub for /api/claude, gated by RESUMI_MOCK. Lets you drive
// the full Workspace -> Tailor -> Review flow (and the browser PDF compile)
// with zero Anthropic calls and zero cost. The "tailoring" is a deterministic
// fake transform, not real AI — every response is flagged MOCK. Delete this
// file and the two RESUMI_MOCK guards in route.ts to remove.

const MOCK_WARNING = '⚠ MOCK MODE — generated by the offline stub, not the AI. Content changes are illustrative only.';

const ZERO_USAGE = { inputTokens: 0, outputTokens: 0, costUsd: 0 };

// Returned by extract_resume regardless of the uploaded file (we can't parse it
// without the AI). Modifying works on whatever structure it's given, so this is
// enough to exercise the feature.
const SAMPLE_STRUCTURE: ResumeStructure = {
  name: 'Alex Ndubuisi',
  contact: { phone: '123-456-7890', email: 'alex@example.com', linkedin: 'linkedin.com/in/alex', github: 'github.com/alex' },
  summary: 'Full-stack developer with a focus on shipping reliable web apps.',
  education: [
    { school: 'University of Toronto', location: 'Toronto, ON', degree: 'BSc Computer Science', dates: 'Sep. 2021 -- May 2025' },
  ],
  experience: [
    {
      title: 'Software Engineering Intern', dates: 'May 2024 -- Aug 2024', org: 'Acme Corp', location: 'Remote',
      bullets: ['Built a REST API in Python serving internal dashboards', 'Improved page load times by profiling hot paths'],
    },
  ],
  projects: [
    { name: 'Resumi', tech: 'Next.js, TypeScript', dates: '2025', bullets: ['Tailors resumes to a job posting', 'Renders an ATS-safe PDF via LaTeX'] },
  ],
  skills: [
    { category: 'Languages', items: 'Python, TypeScript, SQL' },
    { category: 'Tools', items: 'Git, Docker, Vercel' },
  ],
};

const clone = <T,>(v: T): T => JSON.parse(JSON.stringify(v));

function mockTailor(structure: ResumeStructure, jobPosting: any) {
  const s = clone(structure);
  const role = jobPosting?.role || 'the target role';
  const company = jobPosting?.company || 'the company';

  s.summary = `Candidate aligned to ${role} at ${company}. ${s.summary || ''}`.trim();
  if (s.experience[0]?.bullets[0]) {
    s.experience[0].bullets[0] = `[${role}-aligned] ${s.experience[0].bullets[0]}`;
  }
  s.skills = [...s.skills].reverse(); // visible reorder

  return {
    structure: s,
    log: [
      `Reframed the summary around ${role}.`,
      `Emphasised the top experience bullet for ${company}.`,
      'Reordered skill groups to surface the most relevant first.',
    ],
    matchScore: 78,
    missingRequirements: [],
    vague: false,
    vagueReason: '',
    estimatedPages: 1,
    structuralChanges: [],
    warnings: [MOCK_WARNING],
    usage: ZERO_USAGE,
  };
}

function mockInstruct(structure: ResumeStructure, instruction: string) {
  const s = clone(structure);
  if (s.experience[0]?.bullets[0]) {
    s.experience[0].bullets[0] = `[edited] ${s.experience[0].bullets[0]}`;
  }
  return {
    structure: s,
    log: [`Applied instruction: "${instruction}".`],
    estimatedPages: 1,
    warnings: [MOCK_WARNING],
    usage: ZERO_USAGE,
  };
}

/**
 * Returns the response body for a mocked /api/claude POST, or null for an
 * unknown mode.
 *
 * Null rather than a default tailor response so mock mode rejects an unknown
 * mode exactly as the real dispatch table does — a mock that silently accepted
 * anything would hide mode typos during offline testing, which is precisely
 * when they are cheapest to catch.
 */
export function mockApiResponse(body: any) {
  switch (body?.mode) {
    case 'extract':
      return { company: 'Acme Inc', role: 'Software Engineer', description: 'Build and ship web apps with TypeScript and React. (mock job description)' };
    case 'extract_resume':
      return { structure: SAMPLE_STRUCTURE };
    case 'instruct':
      return mockInstruct(body.structure || SAMPLE_STRUCTURE, body.instruction || '');
    case 'tailor':
      return mockTailor(body.structure || SAMPLE_STRUCTURE, body.jobPosting);
    default:
      return null;
  }
}
